{% set version = "3.1.5" %}

package:
  name: graphql-relay
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphql-relay/graphql-relay-{{ version }}.tar.gz
  sha256: 127f40913f11cb847452ef794931261aae3b222eaaf976f7c8430298534e54d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1,<2
  run:
    - python >=3.6
    - graphql-core >=3.1,<3.2
    - typing_extensions >=4,<5

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=6.2,<7
    - pytest-asyncio >=0.14,<1
    - pytest-cov >=2.11,<3
    - pytest-describe >=1,<2
    - pyyaml >=5.4,<6
  imports:
    - graphql_relay
  commands:
    - pip check
    - pytest --cov graphql_relay --no-cov-on-fail --cov-report term-missing:skip-covered --cov-fail-under 91

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Relay library for graphql-core

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
