{% set name = "graphql-relay" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 7fa74661246e826ef939ee92e768f698df167a7617361ab399901eaebf80dce6
    folder: dist
  - url: https://github.com/graphql-python/{{ name }}-py/archive/v{{ version }}.tar.gz
    sha256: 87164f7997ce9c1e8492730683f649d76a01f150706711bafe935e14941217a7
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.12
    - graphql-core >=2.2,<3
    - promise >=2.2,<3

test:
  source_files:
    - src/tests
  requires:
    - pytest-cov
  imports:
    - graphql_relay
    - graphql_relay.connection
    - graphql_relay.mutation
    - graphql_relay.node
  commands:
    - cd src && pytest --cov graphql_relay

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Relay implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-relay-py

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
