{% set name = "graphql-relay" %}
{% set version = "0.4.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2716b7245d97091af21abf096fabafac576905096d21ba7118fba722596f65db" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - six >=1.10.0
    - graphql-core >=0.5.0
    - promise >=0.4.0

test:
  imports:
    - graphql_relay
    - graphql_relay.connection
    - graphql_relay.mutation
    - graphql_relay.node

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: 'Relay implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-relay-py

extra:
  recipe-maintainers:
    - pmlandwehr
