{% set name = "graphql-relay" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/graphql-python/{{ name }}-py/archive/v{{ version }}.tar.gz
  sha256: 87164f7997ce9c1e8492730683f649d76a01f150706711bafe935e14941217a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.12
    - graphql-core >=2.2,<3
    - promise >=2.2,<3

test:
  requires:
    - pytest-cov
  imports:
    - graphql_relay
  commands:
    - pytest --pyargs graphql_relay --cov graphql_relay

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Relay implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-relay-py

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
