{% set name = "graphql-relay" %}
{% set version = "3.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/graphql-python/{{ name }}-py/archive/v{{ version }}.tar.gz
  sha256: 2eb409908aa077cf50638ba9d9b36faa74cdc0cd304196e2cee3f6ff1a01835b

build:
  noarch: python
  number: 0
  script:
    - python -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.6,<4.0.0a0
    - poetry-core >=1,<2
  run:
    - python >=3.6,<4.0.0a0
    - graphql-core >=3.1,<4
    - typing_extensions >=3.6.2,<4

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=6.2,<7
    - pytest-asyncio >=0.14,<1
    - pytest-cov >=2.11,<3
    - pytest-describe >=1,<2
    - pyyaml >=5.4,<6
  imports:
    - graphql_relay
  commands:
    - pip check
    - pytest --cov graphql_relay --no-cov-on-fail --cov-fail-under 91 --cov-report term-missing:skip-covered

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Relay library for graphql-core

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
