{% set name = "graphql-relay" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/graphql-python/{{ name }}-py/archive/v{{ version }}.tar.gz
  sha256: 56b9a3f10da74ba6305d9f1ddf9e3e50ce68dcbd54311c4f83cc8ea55c2dde79

build:
  noarch: python
  number: 0
  script:
    - python -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.6,<4.0.0a0
  run:
    - python >=3.6,<4.0.0a0
    - graphql-core >=3.0.0

test:
  source_files:
    - tests
  requires:
    - pytest-cov >=2.8,<3
    - pytest-describe >=0.12,<1
    - pytest-asyncio >=0.10,<1
  imports:
    - graphql_relay
  commands:
    - pytest --cov graphql_relay

about:
  home: https://github.com/graphql-python/graphql-relay-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Relay library for graphql-core'
  dev_url: https://github.com/graphql-python/graphql-relay-py

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
