travis:
  secure:
    BINSTAR_TOKEN: NJ+0B8njnrJ0bfKAoB4tPqSiyiID02yquMLDpQ0HDLz1FMZaKzholNYld74HG+8zLHvKF8hH9D+i2DbtUvU8pzS4jsb8iP9VaMLFa/+o91ziO23USV24TxCVsgqQBb+tf3se9RPSBjLXetFmTndkqNuMDEBW4rRfX+p2Ic+NcKuujsPr6eYdltrHlnlS6OTO7VDxX0d7LaNhNB2oIH3CTHtNHuaabOJKtLSNZzNe9Aldy1M1/wG14iXR0m93vV1hIGRGslWRF9XLwnuuiaLe2IwA/0N8DZiXTS165c3M8DHvXGj0ZWtCNWojIxKzkKFZOjXBPq1axWGFZ4NQpbioRu45WhFMlqaDr2V/DTJlHz5+2WZkt06Fa94QWhrv2TdJ8jANTLG58eJ5vEApTG+byy9ImOqy24Ofgt738MVQ3qyAH4VgXwGPgR8yBLxBKctVTN9F/NG7X5iU+Kl4iOy9NBwxnovIx6FLy79iRhaPxJFWzEOKswvJgLLwQ9aqfsxBzfPVvq8EuwGwl6NCCC0DFHPinEI1sfaxf3e92zrNnl9iNOqhUpmDDsCn8Tl9FO2tPaWsG9R5WRbKb7FDFSWG3e0SZKOnCGrCx9V3/oFVMPinluXOrRDjRJ486s2uUlXW4SNbJfliPOeZp3Ipbd9n8u0Pbp7d0T5/+V/ikl27LmA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
